# Generated by Django 5.1 on 2024-08-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
